name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate Docker to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Frontend Image
        run: |
          cd frontend  # Change to your frontend directory
          docker build -t capstone_proj:frontend .  # Tag for frontend
          docker tag capstone_proj:frontend ${{ secrets.ECR_REGISTRY }}/capstone_proj:frontend

      - name: Push Frontend Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/capstone_proj:frontend

      - name: Build Backend Image
        run: |
          cd ../backend  # Change to your backend directory
          docker build -t capstone_proj:backend .  # Tag for backend
          docker tag capstone_proj:backend ${{ secrets.ECR_REGISTRY }}/capstone_proj:backend

      - name: Push Backend Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/capstone_proj:backend
