name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step to build and push backend image
    - name: Build and Push Backend
      run: |
        cd backend
        docker build -t backend .
        docker tag back_end:latest 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj/back_end:latest
        docker push 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj/back_end:latest

    # Step to build and push frontend image
    - name: Build and Push Frontend
      run: |
        cd front_end
        docker build -t frontend .
        docker tag front_end:latest 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj/front_end:latest
        docker push 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj/front_end:latest
