name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Create the ECR repository if it doesn't exist
      - name: Create ECR repository
        run: |
          aws ecr describe-repositories --repository-names capstone_proj_frontend || \
          aws ecr create-repository --repository-name capstone_proj_frontend

          aws ecr describe-repositories --repository-names capstone_proj_backend || \
          aws ecr create-repository --repository-name capstone_proj_backend

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050161532.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Backend Docker image
        run: docker build -t capstone_proj_backend ./backend

      - name: Build Frontend Docker image
        run: docker build -t capstone_proj_frontend ./frontend

      - name: Tag and Push Backend Docker image to ECR
        run: |
          docker tag capstone_proj_backend:latest 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj_backend:latest
          docker push 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj_backend:latest

      - name: Tag and Push Frontend Docker image to ECR
        run: |
          docker tag capstone_proj_frontend:latest 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj_frontend:latest
          docker push 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj_frontend:latest
